[workspace]
authors = ["Mike Martinez <mike.j.martinez99@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "cellrank"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


[dependencies]
python = "3.11.*"
pip = "*"
ipykernel = "*"
multivelo = "*"
cellrank = ">=2.0"
loompy = ">=3.0.8,<4"
moscot = ">=0.3.4,<0.4"
ott-jax = ">=0.4.4,<0.4.7"
jax = ">=0.4.20,<0.4.30"
jaxlib = ">=0.4.20,<0.4.30"
plotnine = "*"
python-igraph = "*"

